import styles from './CVPreview.module.css'

export default function CVPreview({ cvData, template }) {
  const { name, title, email, phone, location, link, summary, skills, langs, exps = [], edus = [] } = cvData

  const contact = [email, phone, location, link].filter(Boolean).join(' · ')
  const skillList = (skills || '').split(',').map(s => s.trim()).filter(Boolean)
  const initials = (name || 'ET').split(' ').slice(0, 2).map(w => w[0] || '').join('').toUpperCase()

  const ExpEntry = ({ exp }) => {
    if (template === 'harvard') return (
      <div className={styles.entry}>
        <div className={styles.entryHead}>
          <div>
            <div className={styles.org}>{exp.org || 'Organization'}</div>
            <div className={styles.role}>{exp.role || 'Title'}</div>
          </div>
          <div className={styles.date}>{exp.date || '2020 — Present'}</div>
        </div>
        <div className={styles.desc}>{exp.desc}</div>
      </div>
    )
    if (template === 'modern') return (
      <div className={styles.entry}>
        <div className={styles.org}>{exp.org || 'Organization'}</div>
        <div className={`${styles.role} ${styles.roleBlue}`}>{exp.role || 'Title'}</div>
        <div className={styles.date}>{exp.date || '2020 — Present'}</div>
        <div className={styles.desc}>{exp.desc}</div>
      </div>
    )
    if (template === 'executive') return (
      <div className={styles.entryExec}>
        <div className={styles.date}>{exp.date || '2020 — Present'}</div>
        <div>
          <div className={styles.org}>{exp.org || 'Organization'}</div>
          <div className={`${styles.role} ${styles.roleBlue}`}>{exp.role || 'Title'}</div>
          <div className={styles.desc}>{exp.desc}</div>
        </div>
      </div>
    )
    return null
  }

  const EduEntry = ({ edu }) => {
    if (template === 'harvard') return (
      <div className={styles.entry}>
        <div className={styles.entryHead}>
          <div>
            <div className={styles.org}>{edu.org || 'Institution'}</div>
            <div className={styles.role}>{edu.role || 'Degree'}</div>
          </div>
          <div className={styles.date}>{edu.date || '2019'}</div>
        </div>
      </div>
    )
    if (template === 'modern') return (
      <div className={styles.entry}>
        <div className={styles.org}>{edu.org || 'Institution'}</div>
        <div className={styles.role}>{edu.role || 'Degree'}</div>
        <div className={styles.date}>{edu.date || '2019'}</div>
      </div>
    )
    if (template === 'executive') return (
      <div className={styles.entryExec}>
        <div className={styles.date}>{edu.date || '2019'}</div>
        <div>
          <div className={styles.org}>{edu.org || 'Institution'}</div>
          <div className={styles.role}>{edu.role || 'Degree'}</div>
        </div>
      </div>
    )
    return null
  }

  if (template === 'harvard') return (
    <div className={`${styles.paper} ${styles.harvard}`}>
      <div className={styles.harvardHeader}>
        <div className={styles.harvardName}>{name || 'Your Name'}</div>
        <div className={styles.harvardTitle}>{title || 'Professional Title'}</div>
        <div className={styles.harvardContact}>
          {contact.split('·').map((c, i) => <span key={i}>{c.trim()}</span>)}
        </div>
      </div>
      <div className={styles.body}>
        <div className={styles.sectionTitle}>Executive Presence</div>
        <p className={styles.summaryText}>{summary || 'Your professional summary will appear here.'}</p>
        <div className={styles.sectionTitle}>Selected Experience</div>
        {exps.map((exp, i) => <ExpEntry key={i} exp={exp} />)}
        <div className={styles.sectionTitle}>Foundation</div>
        {edus.map((edu, i) => <EduEntry key={i} edu={edu} />)}
        <div className={styles.sectionTitle}>Core Assets</div>
        <div className={styles.skillsList}>
          {skillList.map((s, i) => <span key={i} className={styles.skill}>{s}</span>)}
        </div>
        {langs && (<><div className={styles.sectionTitle}>Languages</div><p className={styles.langs}>{langs}</p></>)}
        <div className={styles.paperFooter}>GENERATED BY CURRICULATOR EXECUTIVE SUITE</div>
      </div>
    </div>
  )

  if (template === 'modern') return (
    <div className={`${styles.paper} ${styles.modern}`}>
      <div className={styles.modernHeader}>
        <div className={styles.avatar}>{initials}</div>
        <div>
          <div className={styles.modernName}>{name || 'Your Name'}</div>
          <div className={styles.modernTitle}>{title || 'Professional Title'}</div>
          <div className={styles.modernContact}>
            {contact.split('·').map((c, i) => <span key={i}>{c.trim()}</span>)}
          </div>
        </div>
      </div>
      <div className={styles.modernBody}>
        <div>
          <div className={styles.sectionTitleBlue}>Professional Narrative</div>
          <p className={styles.summaryItalic}>{summary || 'Your professional summary will appear here.'}</p>
          <div className={styles.sectionTitleBlue}>Selected Experience</div>
          {exps.map((exp, i) => <ExpEntry key={i} exp={exp} />)}
          <div className={styles.sectionTitleBlue}>Foundation</div>
          {edus.map((edu, i) => <EduEntry key={i} edu={edu} />)}
        </div>
        <div className={styles.modernSidebar}>
          <div className={styles.sectionTitleBlue}>Core Assets</div>
          {skillList.map((s, i) => <span key={i} className={`${styles.skill} ${styles.skillBlock}`}>{s}</span>)}
          {langs && (<><div className={`${styles.sectionTitleBlue} ${styles.mt1}`}>Languages</div><p className={styles.langsSmall}>{langs.split(',').join('\n')}</p></>)}
        </div>
      </div>
    </div>
  )

  if (template === 'executive') return (
    <div className={`${styles.paper} ${styles.executive}`}>
      <div className={styles.execHeader}>
        <div>
          <div className={styles.execName}>{name || 'Your Name'}</div>
          <div className={styles.execTitle}>{title || 'Professional Title'}</div>
        </div>
        <div className={styles.execContact}>
          {contact.split('·').map((c, i) => <div key={i}>{c.trim()}</div>)}
        </div>
      </div>
      <div className={styles.body}>
        <div className={styles.sectionTitleGold}>Executive Summary</div>
        <p className={styles.summaryExec}>{summary || 'Your professional summary will appear here.'}</p>
        <div className={styles.sectionTitleGold}>Chronology</div>
        {exps.map((exp, i) => <ExpEntry key={i} exp={exp} />)}
        <div className={styles.sectionTitleGold}>Foundation</div>
        {edus.map((edu, i) => <EduEntry key={i} edu={edu} />)}
        <div className={styles.sectionTitleGold}>Competencies</div>
        <div className={styles.skillsList}>
          {skillList.map((s, i) => <span key={i} className={`${styles.skill} ${styles.skillExec}`}>{s}</span>)}
        </div>
        {langs && (<><div className={styles.sectionTitleGold}>Languages</div><p className={styles.langs}>{langs}</p></>)}
        <div className={styles.paperFooter}>GENERATED BY CURRICULATOR EXECUTIVE SUITE</div>
      </div>
    </div>
  )

  return null
}
